# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wg25r/pyCMT/gedlib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wg25r/pyCMT/gedlib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wg25r/pyCMT/gedlib/CMakeFiles /home/wg25r/pyCMT/gedlib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wg25r/pyCMT/gedlib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gxlgedlib

# Build rule for target.
gxlgedlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gxlgedlib
.PHONY : gxlgedlib

# fast build rule for target.
gxlgedlib/fast:
	$(MAKE) -f src/CMakeFiles/gxlgedlib.dir/build.make src/CMakeFiles/gxlgedlib.dir/build
.PHONY : gxlgedlib/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named lsap_solver_tests

# Build rule for target.
lsap_solver_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsap_solver_tests
.PHONY : lsap_solver_tests

# fast build rule for target.
lsap_solver_tests/fast:
	$(MAKE) -f tests/unit_tests/CMakeFiles/lsap_solver_tests.dir/build.make tests/unit_tests/CMakeFiles/lsap_solver_tests.dir/build
.PHONY : lsap_solver_tests/fast

#=============================================================================
# Target rules for targets named ged_env_tests

# Build rule for target.
ged_env_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ged_env_tests
.PHONY : ged_env_tests

# fast build rule for target.
ged_env_tests/fast:
	$(MAKE) -f tests/unit_tests/CMakeFiles/ged_env_tests.dir/build.make tests/unit_tests/CMakeFiles/ged_env_tests.dir/build
.PHONY : ged_env_tests/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) -f tests/unit_tests/CMakeFiles/unit_tests.dir/build.make tests/unit_tests/CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named test_lsape_based_methods

# Build rule for target.
test_lsape_based_methods: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lsape_based_methods
.PHONY : test_lsape_based_methods

# fast build rule for target.
test_lsape_based_methods/fast:
	$(MAKE) -f tests/sspr2018/CMakeFiles/test_lsape_based_methods.dir/build.make tests/sspr2018/CMakeFiles/test_lsape_based_methods.dir/build
.PHONY : test_lsape_based_methods/fast

#=============================================================================
# Target rules for targets named learn_subgraph_depths

# Build rule for target.
learn_subgraph_depths: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 learn_subgraph_depths
.PHONY : learn_subgraph_depths

# fast build rule for target.
learn_subgraph_depths/fast:
	$(MAKE) -f tests/sspr2018/CMakeFiles/learn_subgraph_depths.dir/build.make tests/sspr2018/CMakeFiles/learn_subgraph_depths.dir/build
.PHONY : learn_subgraph_depths/fast

#=============================================================================
# Target rules for targets named learn_walks_depths

# Build rule for target.
learn_walks_depths: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 learn_walks_depths
.PHONY : learn_walks_depths

# fast build rule for target.
learn_walks_depths/fast:
	$(MAKE) -f tests/sspr2018/CMakeFiles/learn_walks_depths.dir/build.make tests/sspr2018/CMakeFiles/learn_walks_depths.dir/build
.PHONY : learn_walks_depths/fast

#=============================================================================
# Target rules for targets named learn_ring_params

# Build rule for target.
learn_ring_params: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 learn_ring_params
.PHONY : learn_ring_params

# fast build rule for target.
learn_ring_params/fast:
	$(MAKE) -f tests/sspr2018/CMakeFiles/learn_ring_params.dir/build.make tests/sspr2018/CMakeFiles/learn_ring_params.dir/build
.PHONY : learn_ring_params/fast

#=============================================================================
# Target rules for targets named sspr2018

# Build rule for target.
sspr2018: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sspr2018
.PHONY : sspr2018

# fast build rule for target.
sspr2018/fast:
	$(MAKE) -f tests/sspr2018/CMakeFiles/sspr2018.dir/build.make tests/sspr2018/CMakeFiles/sspr2018.dir/build
.PHONY : sspr2018/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f tests/ijprai2020/CMakeFiles/run_tests.dir/build.make tests/ijprai2020/CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named train_subgraph

# Build rule for target.
train_subgraph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 train_subgraph
.PHONY : train_subgraph

# fast build rule for target.
train_subgraph/fast:
	$(MAKE) -f tests/ijprai2020/CMakeFiles/train_subgraph.dir/build.make tests/ijprai2020/CMakeFiles/train_subgraph.dir/build
.PHONY : train_subgraph/fast

#=============================================================================
# Target rules for targets named train_walks

# Build rule for target.
train_walks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 train_walks
.PHONY : train_walks

# fast build rule for target.
train_walks/fast:
	$(MAKE) -f tests/ijprai2020/CMakeFiles/train_walks.dir/build.make tests/ijprai2020/CMakeFiles/train_walks.dir/build
.PHONY : train_walks/fast

#=============================================================================
# Target rules for targets named train_ring

# Build rule for target.
train_ring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 train_ring
.PHONY : train_ring

# fast build rule for target.
train_ring/fast:
	$(MAKE) -f tests/ijprai2020/CMakeFiles/train_ring.dir/build.make tests/ijprai2020/CMakeFiles/train_ring.dir/build
.PHONY : train_ring/fast

#=============================================================================
# Target rules for targets named run_ipfp

# Build rule for target.
run_ipfp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_ipfp
.PHONY : run_ipfp

# fast build rule for target.
run_ipfp/fast:
	$(MAKE) -f tests/ijprai2020/CMakeFiles/run_ipfp.dir/build.make tests/ijprai2020/CMakeFiles/run_ipfp.dir/build
.PHONY : run_ipfp/fast

#=============================================================================
# Target rules for targets named train_ml

# Build rule for target.
train_ml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 train_ml
.PHONY : train_ml

# fast build rule for target.
train_ml/fast:
	$(MAKE) -f tests/ijprai2020/CMakeFiles/train_ml.dir/build.make tests/ijprai2020/CMakeFiles/train_ml.dir/build
.PHONY : train_ml/fast

#=============================================================================
# Target rules for targets named ijprai2020

# Build rule for target.
ijprai2020: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ijprai2020
.PHONY : ijprai2020

# fast build rule for target.
ijprai2020/fast:
	$(MAKE) -f tests/ijprai2020/CMakeFiles/ijprai2020.dir/build.make tests/ijprai2020/CMakeFiles/ijprai2020.dir/build
.PHONY : ijprai2020/fast

#=============================================================================
# Target rules for targets named vldbj_test_misc_methods

# Build rule for target.
vldbj_test_misc_methods: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vldbj_test_misc_methods
.PHONY : vldbj_test_misc_methods

# fast build rule for target.
vldbj_test_misc_methods/fast:
	$(MAKE) -f tests/vldbj2020/CMakeFiles/vldbj_test_misc_methods.dir/build.make tests/vldbj2020/CMakeFiles/vldbj_test_misc_methods.dir/build
.PHONY : vldbj_test_misc_methods/fast

#=============================================================================
# Target rules for targets named vldbj_test_lp_based_methods

# Build rule for target.
vldbj_test_lp_based_methods: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vldbj_test_lp_based_methods
.PHONY : vldbj_test_lp_based_methods

# fast build rule for target.
vldbj_test_lp_based_methods/fast:
	$(MAKE) -f tests/vldbj2020/CMakeFiles/vldbj_test_lp_based_methods.dir/build.make tests/vldbj2020/CMakeFiles/vldbj_test_lp_based_methods.dir/build
.PHONY : vldbj_test_lp_based_methods/fast

#=============================================================================
# Target rules for targets named vldbj_test_lsape_based_methods

# Build rule for target.
vldbj_test_lsape_based_methods: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vldbj_test_lsape_based_methods
.PHONY : vldbj_test_lsape_based_methods

# fast build rule for target.
vldbj_test_lsape_based_methods/fast:
	$(MAKE) -f tests/vldbj2020/CMakeFiles/vldbj_test_lsape_based_methods.dir/build.make tests/vldbj2020/CMakeFiles/vldbj_test_lsape_based_methods.dir/build
.PHONY : vldbj_test_lsape_based_methods/fast

#=============================================================================
# Target rules for targets named vldbj_test_best_methods

# Build rule for target.
vldbj_test_best_methods: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vldbj_test_best_methods
.PHONY : vldbj_test_best_methods

# fast build rule for target.
vldbj_test_best_methods/fast:
	$(MAKE) -f tests/vldbj2020/CMakeFiles/vldbj_test_best_methods.dir/build.make tests/vldbj2020/CMakeFiles/vldbj_test_best_methods.dir/build
.PHONY : vldbj_test_best_methods/fast

#=============================================================================
# Target rules for targets named vldbj_train_ml

# Build rule for target.
vldbj_train_ml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vldbj_train_ml
.PHONY : vldbj_train_ml

# fast build rule for target.
vldbj_train_ml/fast:
	$(MAKE) -f tests/vldbj2020/CMakeFiles/vldbj_train_ml.dir/build.make tests/vldbj2020/CMakeFiles/vldbj_train_ml.dir/build
.PHONY : vldbj_train_ml/fast

#=============================================================================
# Target rules for targets named vldbj_train_subgraph

# Build rule for target.
vldbj_train_subgraph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vldbj_train_subgraph
.PHONY : vldbj_train_subgraph

# fast build rule for target.
vldbj_train_subgraph/fast:
	$(MAKE) -f tests/vldbj2020/CMakeFiles/vldbj_train_subgraph.dir/build.make tests/vldbj2020/CMakeFiles/vldbj_train_subgraph.dir/build
.PHONY : vldbj_train_subgraph/fast

#=============================================================================
# Target rules for targets named vldbj_test_ls_based_methods

# Build rule for target.
vldbj_test_ls_based_methods: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vldbj_test_ls_based_methods
.PHONY : vldbj_test_ls_based_methods

# fast build rule for target.
vldbj_test_ls_based_methods/fast:
	$(MAKE) -f tests/vldbj2020/CMakeFiles/vldbj_test_ls_based_methods.dir/build.make tests/vldbj2020/CMakeFiles/vldbj_test_ls_based_methods.dir/build
.PHONY : vldbj_test_ls_based_methods/fast

#=============================================================================
# Target rules for targets named vldbj_train_walks

# Build rule for target.
vldbj_train_walks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vldbj_train_walks
.PHONY : vldbj_train_walks

# fast build rule for target.
vldbj_train_walks/fast:
	$(MAKE) -f tests/vldbj2020/CMakeFiles/vldbj_train_walks.dir/build.make tests/vldbj2020/CMakeFiles/vldbj_train_walks.dir/build
.PHONY : vldbj_train_walks/fast

#=============================================================================
# Target rules for targets named vldbj_train_ring

# Build rule for target.
vldbj_train_ring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vldbj_train_ring
.PHONY : vldbj_train_ring

# fast build rule for target.
vldbj_train_ring/fast:
	$(MAKE) -f tests/vldbj2020/CMakeFiles/vldbj_train_ring.dir/build.make tests/vldbj2020/CMakeFiles/vldbj_train_ring.dir/build
.PHONY : vldbj_train_ring/fast

#=============================================================================
# Target rules for targets named vldbj2020

# Build rule for target.
vldbj2020: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vldbj2020
.PHONY : vldbj2020

# fast build rule for target.
vldbj2020/fast:
	$(MAKE) -f tests/vldbj2020/CMakeFiles/vldbj2020.dir/build.make tests/vldbj2020/CMakeFiles/vldbj2020.dir/build
.PHONY : vldbj2020/fast

#=============================================================================
# Target rules for targets named test_lsape_enum

# Build rule for target.
test_lsape_enum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lsape_enum
.PHONY : test_lsape_enum

# fast build rule for target.
test_lsape_enum/fast:
	$(MAKE) -f tests/pvldb2020/CMakeFiles/test_lsape_enum.dir/build.make tests/pvldb2020/CMakeFiles/test_lsape_enum.dir/build
.PHONY : test_lsape_enum/fast

#=============================================================================
# Target rules for targets named pvldb2020

# Build rule for target.
pvldb2020: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pvldb2020
.PHONY : pvldb2020

# fast build rule for target.
pvldb2020/fast:
	$(MAKE) -f tests/pvldb2020/CMakeFiles/pvldb2020.dir/build.make tests/pvldb2020/CMakeFiles/pvldb2020.dir/build
.PHONY : pvldb2020/fast

#=============================================================================
# Target rules for targets named ibd_tests

# Build rule for target.
ibd_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ibd_tests
.PHONY : ibd_tests

# fast build rule for target.
ibd_tests/fast:
	$(MAKE) -f median/CMakeFiles/ibd_tests.dir/build.make median/CMakeFiles/ibd_tests.dir/build
.PHONY : ibd_tests/fast

#=============================================================================
# Target rules for targets named cluster_letter

# Build rule for target.
cluster_letter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cluster_letter
.PHONY : cluster_letter

# fast build rule for target.
cluster_letter/fast:
	$(MAKE) -f median/CMakeFiles/cluster_letter.dir/build.make median/CMakeFiles/cluster_letter.dir/build
.PHONY : cluster_letter/fast

#=============================================================================
# Target rules for targets named indexing_tests

# Build rule for target.
indexing_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 indexing_tests
.PHONY : indexing_tests

# fast build rule for target.
indexing_tests/fast:
	$(MAKE) -f median/CMakeFiles/indexing_tests.dir/build.make median/CMakeFiles/indexing_tests.dir/build
.PHONY : indexing_tests/fast

#=============================================================================
# Target rules for targets named cluster

# Build rule for target.
cluster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cluster
.PHONY : cluster

# fast build rule for target.
cluster/fast:
	$(MAKE) -f median/CMakeFiles/cluster.dir/build.make median/CMakeFiles/cluster.dir/build
.PHONY : cluster/fast

#=============================================================================
# Target rules for targets named clustering_tests

# Build rule for target.
clustering_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clustering_tests
.PHONY : clustering_tests

# fast build rule for target.
clustering_tests/fast:
	$(MAKE) -f median/CMakeFiles/clustering_tests.dir/build.make median/CMakeFiles/clustering_tests.dir/build
.PHONY : clustering_tests/fast

#=============================================================================
# Target rules for targets named bst

# Build rule for target.
bst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bst
.PHONY : bst

# fast build rule for target.
bst/fast:
	$(MAKE) -f median/CMakeFiles/bst.dir/build.make median/CMakeFiles/bst.dir/build
.PHONY : bst/fast

#=============================================================================
# Target rules for targets named aids_edit_iso_test

# Build rule for target.
aids_edit_iso_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aids_edit_iso_test
.PHONY : aids_edit_iso_test

# fast build rule for target.
aids_edit_iso_test/fast:
	$(MAKE) -f median/CMakeFiles/aids_edit_iso_test.dir/build.make median/CMakeFiles/aids_edit_iso_test.dir/build
.PHONY : aids_edit_iso_test/fast

#=============================================================================
# Target rules for targets named median

# Build rule for target.
median: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 median
.PHONY : median

# fast build rule for target.
median/fast:
	$(MAKE) -f median/CMakeFiles/median.dir/build.make median/CMakeFiles/median.dir/build
.PHONY : median/fast

#=============================================================================
# Target rules for targets named time_limit_tests

# Build rule for target.
time_limit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 time_limit_tests
.PHONY : time_limit_tests

# fast build rule for target.
time_limit_tests/fast:
	$(MAKE) -f median/CMakeFiles/time_limit_tests.dir/build.make median/CMakeFiles/time_limit_tests.dir/build
.PHONY : time_limit_tests/fast

#=============================================================================
# Target rules for targets named median_tests

# Build rule for target.
median_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 median_tests
.PHONY : median_tests

# fast build rule for target.
median_tests/fast:
	$(MAKE) -f median/CMakeFiles/median_tests.dir/build.make median/CMakeFiles/median_tests.dir/build
.PHONY : median_tests/fast

#=============================================================================
# Target rules for targets named classification_tests

# Build rule for target.
classification_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 classification_tests
.PHONY : classification_tests

# fast build rule for target.
classification_tests/fast:
	$(MAKE) -f median/CMakeFiles/classification_tests.dir/build.make median/CMakeFiles/classification_tests.dir/build
.PHONY : classification_tests/fast

#=============================================================================
# Target rules for targets named bst_init_letter

# Build rule for target.
bst_init_letter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bst_init_letter
.PHONY : bst_init_letter

# fast build rule for target.
bst_init_letter/fast:
	$(MAKE) -f median/CMakeFiles/bst_init_letter.dir/build.make median/CMakeFiles/bst_init_letter.dir/build
.PHONY : bst_init_letter/fast

#=============================================================================
# Target rules for targets named median_letter_demo

# Build rule for target.
median_letter_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 median_letter_demo
.PHONY : median_letter_demo

# fast build rule for target.
median_letter_demo/fast:
	$(MAKE) -f median/CMakeFiles/median_letter_demo.dir/build.make median/CMakeFiles/median_letter_demo.dir/build
.PHONY : median_letter_demo/fast

#=============================================================================
# Target rules for targets named bst_query_letter

# Build rule for target.
bst_query_letter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bst_query_letter
.PHONY : bst_query_letter

# fast build rule for target.
bst_query_letter/fast:
	$(MAKE) -f median/CMakeFiles/bst_query_letter.dir/build.make median/CMakeFiles/bst_query_letter.dir/build
.PHONY : bst_query_letter/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... gxlgedlib"
	@echo "... tests"
	@echo "... lsap_solver_tests"
	@echo "... ged_env_tests"
	@echo "... unit_tests"
	@echo "... test_lsape_based_methods"
	@echo "... learn_subgraph_depths"
	@echo "... learn_walks_depths"
	@echo "... learn_ring_params"
	@echo "... sspr2018"
	@echo "... run_tests"
	@echo "... train_subgraph"
	@echo "... train_walks"
	@echo "... train_ring"
	@echo "... run_ipfp"
	@echo "... train_ml"
	@echo "... ijprai2020"
	@echo "... vldbj_test_misc_methods"
	@echo "... vldbj_test_lp_based_methods"
	@echo "... vldbj_test_lsape_based_methods"
	@echo "... vldbj_test_best_methods"
	@echo "... vldbj_train_ml"
	@echo "... vldbj_train_subgraph"
	@echo "... vldbj_test_ls_based_methods"
	@echo "... vldbj_train_walks"
	@echo "... vldbj_train_ring"
	@echo "... vldbj2020"
	@echo "... test_lsape_enum"
	@echo "... pvldb2020"
	@echo "... ibd_tests"
	@echo "... cluster_letter"
	@echo "... indexing_tests"
	@echo "... cluster"
	@echo "... clustering_tests"
	@echo "... bst"
	@echo "... aids_edit_iso_test"
	@echo "... median"
	@echo "... time_limit_tests"
	@echo "... median_tests"
	@echo "... classification_tests"
	@echo "... bst_init_letter"
	@echo "... median_letter_demo"
	@echo "... bst_query_letter"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

